# -*- coding: utf-8 -*-
"""SWA_FakeNewsNet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14koLh1ZlSs4TPdbQjNIOJaezTPOY733n
"""

import pandas as pd
import numpy as np
import re
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.sparse import hstack, csr_matrix

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    confusion_matrix, classification_report, roc_auc_score, roc_curve
)

RANDOM_STATE = 42
NUMERIC_COLS = ['title_length', 'tweet_count', 'exclaim_count', 'question_count', 'has_url']


# ---------------------------------------------------------------------------
# 1. LOAD & MERGE DATA
# ---------------------------------------------------------------------------
def load_data():
    pf_fake = pd.read_csv('politifact_fake.csv')
    pf_real = pd.read_csv('politifact_real.csv')
    gc_fake = pd.read_csv('gossipcop_fake.csv')
    gc_real = pd.read_csv('gossipcop_real.csv')

    pf_fake['label'], pf_real['label'] = 1, 0        # 1 = fake, 0 = real
    gc_fake['label'], gc_real['label'] = 1, 0
    pf_fake['source'], pf_real['source'] = 'politifact', 'politifact'
    gc_fake['source'], gc_real['source'] = 'gossipcop', 'gossipcop'

    df = pd.concat([pf_fake, pf_real, gc_fake, gc_real], ignore_index=True)
    print(f"Loaded {len(df)} rows total.")
    print(df['source'].value_counts())
    print(df['label'].value_counts().rename({0: 'real', 1: 'fake'}))
    return df


# ---------------------------------------------------------------------------
# 2. CLEANING & FEATURE ENGINEERING
# ---------------------------------------------------------------------------
def clean_text(text):
    """Lowercase, strip URLs/punctuation/extra whitespace."""
    if pd.isna(text):
        return ""
    text = str(text).lower()
    text = re.sub(r'http\S+|www\S+', '', text)         # strip embedded links
    text = re.sub(r'[^a-z0-9\s]', ' ', text)             # drop punctuation/symbols
    text = re.sub(r'\s+', ' ', text).strip()             # collapse extra whitespace
    return text


def count_tweets(tweet_ids):
    """tweet_ids column is a space or tab separated string of IDs."""
    if pd.isna(tweet_ids) or str(tweet_ids).strip() == "":
        return 0
    return len(str(tweet_ids).split())


def engineer_features(df):
    df = df.copy()

    # Drop rows with no title at all - can't use them
    df = df[df['title'].notna() & (df['title'].str.strip() != "")]

    df['clean_title'] = df['title'].apply(clean_text)
    df['title_length'] = df['clean_title'].apply(lambda x: len(x.split()))
    df['tweet_count'] = df['tweet_ids'].apply(count_tweets)

    # Simple "sensationalism" signal - exclamation/question marks.
    df['exclaim_count'] = df['title'].apply(lambda t: str(t).count('!'))
    df['question_count'] = df['title'].apply(lambda t: str(t).count('?'))
    df['has_url'] = df['news_url'].notna().astype(int)

    print(f"\nAfter cleaning: {len(df)} rows remain.")
    return df


# ---------------------------------------------------------------------------
# 2b. EXPLORATORY DATA ANALYSIS (EDA)
# ---------------------------------------------------------------------------
def run_eda(df):
    """
    Generate EDA plots and summary statistics for the dataset.
    """
    sns.set_style('whitegrid')

    # Class balance
    plt.figure(figsize=(6, 5))
    counts = df['label'].value_counts().rename({0: 'Real', 1: 'Fake'})
    sns.barplot(x=counts.index, y=counts.values, hue=counts.index,
                palette=['#4C72B0', '#DD8452'], legend=False)
    plt.title('Class Balance: Real vs Fake News')
    plt.ylabel('Number of Articles')
    for i, v in enumerate(counts.values):
        plt.text(i, v + 100, str(v), ha='center')
    plt.tight_layout()
    plt.savefig('eda_class_balance.png', dpi=150)
    plt.show()
    plt.close()
    print("Saved eda_class_balance.png")

    # Class balance by source
    plt.figure(figsize=(7, 5))
    ct = pd.crosstab(df['source'], df['label']).rename(columns={0: 'Real', 1: 'Fake'})
    ct.plot(kind='bar', stacked=True, color=['#4C72B0', '#DD8452'], ax=plt.gca())
    plt.title('Real vs Fake Counts by Source')
    plt.ylabel('Number of Articles')
    plt.xticks(rotation=0)
    plt.tight_layout()
    plt.savefig('eda_class_by_source.png', dpi=150)
    plt.show()
    plt.close()
    print("Saved eda_class_by_source.png")

    # Title length distribution
    plt.figure(figsize=(7, 5))
    sns.histplot(data=df, x='title_length', hue='label', bins=30,
                 element='step', stat='density', common_norm=False,
                 palette={0: '#4C72B0', 1: '#DD8452'})
    plt.title('Title Length Distribution: Real vs Fake')
    plt.xlabel('Title Length (words)')
    plt.legend(labels=['Fake', 'Real'])
    plt.tight_layout()
    plt.savefig('eda_title_length.png', dpi=150)
    plt.show()
    plt.close()
    print("Saved eda_title_length.png")

    plt.figure(figsize=(7, 5))
    df_plot = df.copy()
    df_plot['log_tweet_count'] = np.log1p(df_plot['tweet_count'])
    sns.histplot(data=df_plot, x='log_tweet_count', hue='label', bins=30,
                 element='step', stat='density', common_norm=False,
                 palette={0: '#4C72B0', 1: '#DD8452'})
    plt.title('Tweet Engagement Distribution: Real vs Fake (log scale)')
    plt.xlabel('log(1 + tweet count)')
    plt.legend(labels=['Fake', 'Real'])
    plt.tight_layout()
    plt.savefig('eda_tweet_count.png', dpi=150)
    plt.show()
    plt.close()
    print("Saved eda_tweet_count.png")

    # Summary stats table
    summary = df.groupby('label')[['title_length', 'tweet_count',
                                    'exclaim_count', 'question_count']].describe()
    summary.to_csv('eda_summary_stats.csv')
    print("Saved eda_summary_stats.csv")
    print("\n=== EDA Summary (by label, 0=real, 1=fake) ===")
    print(df.groupby('label')[['title_length', 'tweet_count',
                                'exclaim_count', 'question_count']].mean())


# ---------------------------------------------------------------------------
# 3. TRAIN / TEST SPLIT
# ---------------------------------------------------------------------------
def split_data(df):
    X = df[['clean_title'] + NUMERIC_COLS]
    y = df['label']

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=RANDOM_STATE, stratify=y
    )
    print(f"\nTrain size: {len(X_train)}, Test size: {len(X_test)}")
    return X_train, X_test, y_train, y_test


# ---------------------------------------------------------------------------
# 4. VECTORIZE TEXT + (OPTIONALLY) COMBINE WITH NUMERIC FEATURES
# ---------------------------------------------------------------------------
def build_features(X_train, X_test, include_numeric=True):
    """
    Build TF-IDF features.
    include_numeric=False: headline-only features
    include_numeric=True: headline + numeric features
    """
    # Convert headlines into TF-IDF features
    tfidf = TfidfVectorizer(max_features=3000, stop_words='english', ngram_range=(1, 2))
    X_train_text = tfidf.fit_transform(X_train['clean_title'])
    X_test_text = tfidf.transform(X_test['clean_title'])

    if not include_numeric:
        return X_train_text, X_test_text, tfidf

    X_train_num = csr_matrix(X_train[NUMERIC_COLS].values)
    X_test_num = csr_matrix(X_test[NUMERIC_COLS].values)

    X_train_final = hstack([X_train_text, X_train_num])
    X_test_final = hstack([X_test_text, X_test_num])

    return X_train_final, X_test_final, tfidf


# ---------------------------------------------------------------------------
# 5. TRAIN MODELS
# ---------------------------------------------------------------------------
def train_models(X_train, y_train):
    """
    Train the selected machine learning classifiers:
    - Multinomial Naive Bayes
    - Logistic Regression
    - Linear SVM
    """
    models = {
        'Multinomial Naive Bayes': MultinomialNB(),
        'Logistic Regression': LogisticRegression(
            max_iter=2000, random_state=RANDOM_STATE, class_weight='balanced'
        ),
        'Linear SVM': LinearSVC(
            random_state=RANDOM_STATE, class_weight='balanced', max_iter=5000
        ),
    }
    for name, model in models.items():
        model.fit(X_train, y_train)
        print(f"Trained: {name}")
    return models


def get_scores(model, X):
    """
    Return predictions and confidence scores for model evaluation.
    """
    y_pred = model.predict(X)
    if hasattr(model, 'predict_proba'):
        y_score = model.predict_proba(X)[:, 1]
    else:
        raw = model.decision_function(X)
        y_score = 1 / (1 + np.exp(-raw))  # sigmoid squash for SVM decision scores
    return y_pred, y_score


# ---------------------------------------------------------------------------
# 6. EVALUATE & COMPARE
# ---------------------------------------------------------------------------
def evaluate_models(models, X_test, y_test, feature_set_name='', plot_roc=True):
    results = []
    if plot_roc:
        plt.figure(figsize=(7, 6))

    for name, model in models.items():
        y_pred, y_score = get_scores(model, X_test)

        acc = accuracy_score(y_test, y_pred)
        prec = precision_score(y_test, y_pred)
        rec = recall_score(y_test, y_pred)
        f1 = f1_score(y_test, y_pred)
        auc = roc_auc_score(y_test, y_score)

        results.append({
            'Model': name, 'Accuracy': acc, 'Precision': prec,
            'Recall': rec, 'F1': f1, 'ROC_AUC': auc
        })

        label = f"{feature_set_name} - {name}" if feature_set_name else name
        print(f"\n--- {label} ---")
        print(classification_report(y_test, y_pred, target_names=['real', 'fake']))
        cm = confusion_matrix(y_test, y_pred)
        print("Confusion matrix:\n", cm)

        # --- Save confusion matrix as a heatmap image for the report ---
        plt.figure(figsize=(5, 4))
        sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                    xticklabels=['Real', 'Fake'], yticklabels=['Real', 'Fake'])
        plt.title(f'Confusion Matrix: {label}')
        plt.xlabel('Predicted')
        plt.ylabel('Actual')
        plt.tight_layout()
        cm_fname = f"cm_{feature_set_name.lower().replace(' ', '_')}_{name.lower().replace(' ', '_')}.png" \
            if feature_set_name else f"cm_{name.lower().replace(' ', '_')}.png"
        plt.savefig(cm_fname, dpi=150)
        plt.show()
        plt.close()
        print(f"Saved confusion matrix chart to {cm_fname}")

        if plot_roc:
            fpr, tpr, _ = roc_curve(y_test, y_score)
            plt.plot(fpr, tpr, label=f"{name} (AUC={auc:.2f})")

    if plot_roc:
        plt.plot([0, 1], [0, 1], linestyle='--', color='gray')
        plt.xlabel('False Positive Rate')
        plt.ylabel('True Positive Rate')
        title_suffix = f' ({feature_set_name})' if feature_set_name else ''
        plt.title(f'ROC Curves - Model Comparison{title_suffix}')
        plt.legend()
        plt.tight_layout()
        fname = f"roc_comparison_{feature_set_name.lower().replace(' ', '_')}.png" \
            if feature_set_name else "roc_comparison.png"
        plt.savefig(fname, dpi=150)
        plt.show()
        plt.close()
        print(f"\nSaved ROC comparison chart to {fname}")

    results_df = pd.DataFrame(results).sort_values('F1', ascending=False)
    print(f"\n=== Model Comparison Table ({feature_set_name}) ===")
    print(results_df.to_string(index=False))
    return results_df


# ---------------------------------------------------------------------------
# 6b. FEATURE IMPORTANCE (Discussion section material)
# ---------------------------------------------------------------------------
def plot_feature_importance(model, tfidf, top_n=20, include_numeric=True):
    """
    Plot important features from linear model coefficients.
    """
    if hasattr(model, 'coef_'):
        importances = np.abs(model.coef_).flatten()
    else:
        print("Selected model has no coef_ (Naive Bayes) - skipping feature importance plot.")
        return

    text_feature_names = list(tfidf.get_feature_names_out())
    all_feature_names = text_feature_names + (NUMERIC_COLS if include_numeric else [])

    fi_df = pd.DataFrame({
        'feature': all_feature_names,
        'importance': importances
    }).sort_values('importance', ascending=False).head(top_n)

    plt.figure(figsize=(8, 7))
    sns.barplot(data=fi_df, y='feature', x='importance', color='#4C72B0')
    plt.title(f'Top {top_n} Most Important Features')
    plt.xlabel('|Coefficient| (feature importance)')
    plt.tight_layout()
    plt.savefig('feature_importance.png', dpi=150)
    plt.show()
    plt.close()
    print("Saved feature_importance.png")

    fi_df.to_csv('feature_importance.csv', index=False)
    print("Saved feature_importance.csv")


# ---------------------------------------------------------------------------
# 7. EXPORT FOR POWER BI
# ---------------------------------------------------------------------------
def export_for_powerbi(best_model, X_test_final, X_test, y_test):
    # Export prediction results for Power BI visualization
    y_pred, y_score = get_scores(best_model, X_test_final)

    export_df = X_test.copy()
    export_df['actual_label'] = y_test.values
    export_df['predicted_label'] = y_pred
    export_df['fake_score'] = y_score
    export_df['correct'] = (export_df['actual_label'] == export_df['predicted_label'])

    export_df.to_csv('powerbi_export.csv', index=False)
    print("\nSaved prediction results to powerbi_export.csv (import this into Power BI)")


# ---------------------------------------------------------------------------
# MAIN
# ---------------------------------------------------------------------------
def main():
    df = load_data()
    df = engineer_features(df)

    run_eda(df)  # generates eda_*.png / eda_summary_stats.csv

    X_train, X_test, y_train, y_test = split_data(df)

    # Headline-only features
    print("\n=========== FEATURE SET: HEADLINE-ONLY ===========")
    X_train_h, X_test_h, tfidf_h = build_features(X_train, X_test, include_numeric=False)
    models_headline = train_models(X_train_h, y_train)
    results_headline = evaluate_models(models_headline, X_test_h, y_test,
                                        feature_set_name='Headline-only')
    results_headline['FeatureSet'] = 'Headline-only'

    # Combined features: headline + numeric features
    print("\n=========== FEATURE SET: COMBINED (HEADLINE + SHARING) ===========")
    X_train_c, X_test_c, tfidf_c = build_features(X_train, X_test, include_numeric=True)
    models_combined = train_models(X_train_c, y_train)
    results_combined = evaluate_models(models_combined, X_test_c, y_test,
                                        feature_set_name='Combined')
    results_combined['FeatureSet'] = 'Combined'

    # Combine both arms into one comparison table for the report
    comparison = pd.concat([results_headline, results_combined], ignore_index=True)
    comparison = comparison[['FeatureSet', 'Model', 'Accuracy', 'Precision',
                              'Recall', 'F1', 'ROC_AUC']]
    comparison.to_csv('model_comparison.csv', index=False)
    print("\n=== Headline-only vs Combined Comparison (all models) ===")
    print(comparison.to_string(index=False))
    print("\nSaved model_comparison.csv (use this table in your report's Results section)")

    best_model_name = results_combined.sort_values('F1', ascending=False).iloc[0]['Model']
    best_model = models_combined[best_model_name]
    print(f"\nBest model (combined features) by F1 score: {best_model_name}")

    plot_feature_importance(best_model, tfidf_c, include_numeric=True)
    export_for_powerbi(best_model, X_test_c, X_test, y_test)


if __name__ == '__main__':
    main()